/**
 * Censo Demostrativo y Piloto Comunitario
 * Datos representativos levantados en Arroz Barato y Nelson Mandela (Cartagena D.T. y C.)
 * Utilizados como respaldo analítico y visualización en tiempo real.
 */
import { computeAssignedPrograms } from './sendaPrograms';

const RAW_DEMO_SURVEYS: any[] = [
  {
    _id: 'demo-arz-001',
    surveyCode: 'CS-ARZ-001',
    barrio: 'Arroz Barato',
    manzana: 'Mz 14 Lote 3',
    visitDate: '2026-08-15T09:30:00.000Z',
    collectorName: 'Lic. Claudia Mendoza',
    collectorCode: 'C-04',
    fieldZone: 'Sector El Manantial',
    contactPhone: '312-554-8921',
    landmark: 'Frente a la tienda La Esperanza, callejón sin pavimentar',
    householdSize: 5,
    minorCount: 3,
    allDocumentsValid: true,
    allNNASchooled: false,
    schoolDropoutReason: 'Menor de 14 años desertó por falta de cupo y recursos para uniformes',
    hasDisabledMember: false,
    hasElderlyMember: true,
    elderlyCount: 1,
    rooms: 2,
    overcrowdingNotes: 'Hacinamiento crítico: 5 personas en un solo cuarto con tabique de madera',
    allEPSAffiliated: false,
    epsRegime: 'Subsidiado (Mutual Ser)',
    nonAffiliatedReason: 'Abuela de 69 años figura como suspendida en ADRES por inconsistencia de cédula',
    hasPregnantOrLactating: true,
    prenatalCareStatus: 'Gestante de 24 semanas con solo 1 control prenatal asistido',
    vaccinesUpToDate: false,
    vaccineCardAvailable: false,
    hasChronicDisease: true,
    chronicDiseaseDetails: 'Abuela con hipertensión arterial sin medicación desde hace 4 meses',
    hasEDAParasites: true,
    edaDetails: 'Niño de 3 años con diarrea recurrente y distensión abdominal',
    dentalCarePending: true,
    healthcareAccessDifficulty: true,
    healthcareAccessDetails: 'Puesto de salud local cerrado los fines de semana; CAP Arroz Barato saturado',
    waterSource: 'CARROTANQUE',
    psychologicalSupportNeeded: true,
    psychologicalSupportWho: 'Madre cabeza de hogar manifiesta angustia severa y sobrecarga emocional',
    hasSTIHistoryOrSymptoms: true,
    stiSymptomsDetails: 'Flujo anormal fétido y dolor pélvico persistente sin diagnóstico médico',
    lastPapSmear: 'MAS_3_ANOS',
    familyPlanningMethod: 'NINGUNO',
    desiresFamilyPlanningCounseling: true,
    vaginalInfectionSymptoms: true,
    breastSelfExamTrained: false,
    hasMammographyOrUltrasoundNeeded: true,
    hasFamilyProcess: true,
    familyProcessDetails: 'Inasistencia alimentaria del progenitor de los 2 niños menores',
    hasVIFVBG: true,
    vifComplaintFiled: false,
    vifProcessStatus: 'Amenazas verbales y acoso económico por expareja que reside en el mismo sector',
    housingType: 'FAMILIAR',
    hasHousingDocument: false,
    hasDebtOrProcess: true,
    debtDetails: 'Deuda informal con cobradiario al 20% mensual para compra de alimentos',
    needsPensionOrSubsidy: true,
    pensionDetails: 'Abuela sin pensión ni subsidio Colombia Mayor',
    hasUrgentCase: true,
    urgentCaseDescription: 'Gestante sin controles adecuados + violencia intrafamiliar activa con agresor cerca',
    incomeSource: 'Venta ambulante de fritos y lavado de ropa esporádico',
    receivesSubsidies: false,
    hasJobSeeker: true,
    jobSearchDifficulty: 'Sin empleo formal por falta de experiencia certificada',
    hasRecentGraduate: false,
    riskLevel: 'ALTO',
    observedRiskIndicators: 'Vivienda con piso de tierra y láminas de zinc oxidadas; aguas estancadas a la entrada',
    authorizedRecontact: true,
    collectorObservations: 'Prioridad médica y jurídica urgente. Requiere remisión a ginecología y Patrulla Púrpura.',
    activateImmediateRoute: true,
    immediateRouteType: 'Comisaría de Familia + Urgencia Materna DADIS',
    needs: ['salud', 'materna', 'its_ginecologia', 'citologia_urgente', 'violencia', 'familia', 'vivienda'],
    priority: 'INMEDIATA',
    householdMembers: [
      { fullName: 'Yuleidis María Gómez Torres', age: 29, relationship: 'Persona Referente', documentType: 'CC', documentNumber: '1.047.889.213' },
      { fullName: 'Rosaura Torres de Gómez', age: 69, relationship: 'Madre / Abuela', documentType: 'CC', documentNumber: '22.845.119' },
      { fullName: 'Brayan José Gómez', age: 14, relationship: 'Hijo', documentType: 'TI', documentNumber: '1.143.901.882' },
      { fullName: 'Keiler David Gómez', age: 7, relationship: 'Hijo', documentType: 'RC', documentNumber: '1.209.431.112' },
      { fullName: 'Valery Sofía Gómez', age: 3, relationship: 'Hija', documentType: 'RC', documentNumber: '1.288.741.009' },
    ]
  },
  {
    _id: 'demo-arz-002',
    surveyCode: 'CS-ARZ-002',
    barrio: 'Arroz Barato',
    manzana: 'Mz 08 Lote 12',
    visitDate: '2026-08-15T10:45:00.000Z',
    collectorName: 'Dr. Hernán Silva',
    collectorCode: 'M-02',
    fieldZone: 'Sector La Cancha',
    contactPhone: '301-445-1290',
    landmark: 'Atrás del centro comunal, reja azul',
    householdSize: 4,
    minorCount: 2,
    allDocumentsValid: true,
    allNNASchooled: true,
    hasDisabledMember: true,
    disabledDetails: 'Joven de 16 años con parálisis cerebral leve, requiere silla de ruedas ergonómica',
    hasElderlyMember: false,
    elderlyCount: 0,
    rooms: 2,
    allEPSAffiliated: true,
    epsRegime: 'Subsidiado (Cajacopi)',
    hasPregnantOrLactating: false,
    vaccinesUpToDate: true,
    vaccineCardAvailable: true,
    hasChronicDisease: false,
    hasEDAParasites: false,
    dentalCarePending: true,
    healthcareAccessDifficulty: true,
    healthcareAccessDetails: 'Citas de fisioterapia y neuropediatría demoradas más de 6 meses por la EPS',
    waterSource: 'ACUEDUCTO',
    psychologicalSupportNeeded: false,
    hasSTIHistoryOrSymptoms: false,
    lastPapSmear: '1_A_3_ANOS',
    familyPlanningMethod: 'INYECTABLE',
    desiresFamilyPlanningCounseling: false,
    vaginalInfectionSymptoms: false,
    breastSelfExamTrained: true,
    hasMammographyOrUltrasoundNeeded: false,
    hasFamilyProcess: false,
    hasVIFVBG: false,
    housingType: 'PROPIA',
    hasHousingDocument: false,
    hasDebtOrProcess: false,
    needsPensionOrSubsidy: true,
    pensionDetails: 'Solicitan inclusión en subsidio de discapacidad distrital',
    hasUrgentCase: false,
    incomeSource: 'Mototaxismo y costura a destajo',
    receivesSubsidies: true,
    subsidiesDetails: 'Renta Ciudadana',
    hasJobSeeker: false,
    hasRecentGraduate: false,
    riskLevel: 'MEDIO',
    collectorObservations: 'Hogar funcional con alta carga de cuidado. Requiere apoyo ortopédico y gestión ante EPS.',
    activateImmediateRoute: false,
    needs: ['salud', 'acceso_salud', 'subsidios', 'vivienda'],
    priority: 'PRIORITARIA',
    householdMembers: [
      { fullName: 'Doris Cecilia Paternina', age: 41, relationship: 'Persona Referente', documentType: 'CC', documentNumber: '45.712.980' },
      { fullName: 'Carlos Alberto Sierra', age: 44, relationship: 'Cónyuge', documentType: 'CC', documentNumber: '73.190.542' },
      { fullName: 'Mateo Sierra Paternina', age: 16, relationship: 'Hijo (Condición de discapacidad)', documentType: 'TI', documentNumber: '1.098.223.411' },
      { fullName: 'Camila Andrea Sierra', age: 10, relationship: 'Hija', documentType: 'TI', documentNumber: '1.144.567.890' },
    ]
  },
  {
    _id: 'demo-arz-003',
    surveyCode: 'CS-ARZ-003',
    barrio: 'Arroz Barato',
    manzana: 'Mz 22 Lote 7',
    visitDate: '2026-08-15T11:30:00.000Z',
    collectorName: 'Dra. Mileidys Romero',
    collectorCode: 'G-01',
    fieldZone: 'Sector La Loma',
    contactPhone: '320-987-6543',
    landmark: 'Calle del Tanque, casa de madera pintada de blanco',
    householdSize: 6,
    minorCount: 4,
    allDocumentsValid: false,
    documentsIssue: '2 niños con solo registro civil venezolano sin Permiso por Protección Temporal (PPT)',
    allNNASchooled: false,
    schoolDropoutReason: 'Falta de regularización migratoria impidió matrícula oficial en SIMAT',
    hasDisabledMember: false,
    hasElderlyMember: false,
    rooms: 1,
    overcrowdingNotes: '6 personas durmiendo en un solo espacio sin ventilación adecuada',
    allEPSAffiliated: false,
    nonAffiliatedReason: 'Madre y 3 menores sin afiliación activa a salud por estatus migratorio en trámite',
    hasPregnantOrLactating: true,
    prenatalCareStatus: 'Lactante de 5 meses con retraso en esquema de vacunación y bajo peso',
    vaccinesUpToDate: false,
    vaccineCardAvailable: false,
    hasChronicDisease: false,
    hasEDAParasites: true,
    edaDetails: 'Lactante y niña de 4 años con episodios de diarrea aguda y deshidratación leve',
    dentalCarePending: true,
    healthcareAccessDifficulty: true,
    healthcareAccessDetails: 'Temor a acudir a centros de salud por estado documental',
    waterSource: 'PILA_PUBLICA',
    psychologicalSupportNeeded: true,
    psychologicalSupportWho: 'Madre joven de 22 años aislada socialmente',
    hasSTIHistoryOrSymptoms: true,
    stiSymptomsDetails: 'Lesiones genitales ulcerosas y dolor intenso, probable infección herpética o sífilis',
    lastPapSmear: 'NUNCA',
    familyPlanningMethod: 'NINGUNO',
    desiresFamilyPlanningCounseling: true,
    vaginalInfectionSymptoms: true,
    breastSelfExamTrained: false,
    hasMammographyOrUltrasoundNeeded: false,
    hasFamilyProcess: false,
    hasVIFVBG: false,
    housingType: 'ARRENDADA',
    hasHousingDocument: false,
    hasDebtOrProcess: false,
    needsPensionOrSubsidy: false,
    hasUrgentCase: true,
    urgentCaseDescription: 'Lesiones por sospecha de ITS activa + lactante con desnutrición aguda y sin vacunas',
    incomeSource: 'Reciclaje y venta de dulces en semáforos',
    receivesSubsidies: false,
    hasJobSeeker: true,
    jobSearchDifficulty: 'Sin permiso de trabajo en Colombia',
    hasRecentGraduate: false,
    riskLevel: 'ALTO',
    collectorObservations: 'Urgencia médica pediátrica y ginecológica. Requiere tamizaje serológico y ruta migratoria.',
    activateImmediateRoute: true,
    immediateRouteType: 'Atención Médica Inmediata + Vacunación Extramural + Migración Colombia',
    needs: ['salud', 'afiliacion', 'materna', 'vacunacion', 'documentacion', 'educacion', 'its_ginecologia', 'citologia_urgente'],
    priority: 'INMEDIATA',
    householdMembers: [
      { fullName: 'Marianyelis Chiquinquirá Rivas', age: 22, relationship: 'Persona Referente', documentType: 'PA', documentNumber: '15.987.234-VZ' },
      { fullName: 'Moisés Alejandro Rivas', age: 6, relationship: 'Hijo', documentType: 'RC', documentNumber: 'SIN_DOC' },
      { fullName: 'Aranza Sofía Rivas', age: 4, relationship: 'Hija', documentType: 'RC', documentNumber: 'SIN_DOC' },
      { fullName: 'Thiago José Rivas', age: 0, relationship: 'Hijo (Lactante 5 meses)', documentType: 'RC', documentNumber: '1.244.908.112' },
      { fullName: 'Grecia Josefina Rivas', age: 19, relationship: 'Hermana', documentType: 'PA', documentNumber: '17.332.109-VZ' },
      { fullName: 'Luis Miguel Rondón', age: 25, relationship: 'Pareja de hermana', documentType: 'PA', documentNumber: '16.441.889-VZ' },
    ]
  },
  {
    _id: 'demo-arz-004',
    surveyCode: 'CS-ARZ-004',
    barrio: 'Arroz Barato',
    manzana: 'Mz 03 Lote 18',
    visitDate: '2026-08-16T08:15:00.000Z',
    collectorName: 'Dra. Vanessa Carvajal',
    collectorCode: 'J-03',
    fieldZone: 'Sector Bellavista',
    contactPhone: '315-776-3342',
    landmark: 'Al lado de la bodega de reciclaje El Sol',
    householdSize: 3,
    minorCount: 1,
    allDocumentsValid: true,
    allNNASchooled: true,
    hasDisabledMember: false,
    hasElderlyMember: false,
    rooms: 2,
    allEPSAffiliated: true,
    epsRegime: 'Contributivo (Sura)',
    hasPregnantOrLactating: false,
    vaccinesUpToDate: true,
    vaccineCardAvailable: true,
    hasChronicDisease: true,
    chronicDiseaseDetails: 'Diabetes Mellitus tipo 2 controlada con metformina',
    hasEDAParasites: false,
    dentalCarePending: false,
    healthcareAccessDifficulty: false,
    waterSource: 'ACUEDUCTO',
    psychologicalSupportNeeded: false,
    hasSTIHistoryOrSymptoms: false,
    lastPapSmear: 'MENOS_1_ANO',
    familyPlanningMethod: 'IMPLANTE',
    desiresFamilyPlanningCounseling: false,
    vaginalInfectionSymptoms: false,
    breastSelfExamTrained: true,
    hasMammographyOrUltrasoundNeeded: true,
    hasFamilyProcess: false,
    hasVIFVBG: false,
    housingType: 'PROPIA',
    hasHousingDocument: true,
    hasDebtOrProcess: false,
    needsPensionOrSubsidy: false,
    hasUrgentCase: false,
    incomeSource: 'Empleado en zona industrial de Mamonal',
    receivesSubsidies: false,
    hasJobSeeker: false,
    hasRecentGraduate: false,
    riskLevel: 'BAJO',
    collectorObservations: 'Hogar estable con buenas condiciones de habitabilidad. Se agenda para tamizaje de mamografía.',
    activateImmediateRoute: false,
    needs: ['salud', 'cronica'],
    priority: 'NORMAL',
    householdMembers: [
      { fullName: 'Gladys Ester Beltrán Ortiz', age: 52, relationship: 'Persona Referente', documentType: 'CC', documentNumber: '33.123.456' },
      { fullName: 'Jorge Enrique Castro Beltrán', age: 30, relationship: 'Hijo', documentType: 'CC', documentNumber: '1.047.456.789' },
      { fullName: 'Samuel Castro Morales', age: 8, relationship: 'Nieto', documentType: 'TI', documentNumber: '1.144.112.334' },
    ]
  },
  {
    _id: 'demo-arz-005',
    surveyCode: 'CS-ARZ-005',
    barrio: 'Arroz Barato',
    manzana: 'Mz 19 Lote 05',
    visitDate: '2026-08-16T09:40:00.000Z',
    collectorName: 'Lic. Claudia Mendoza',
    collectorCode: 'C-04',
    fieldZone: 'Sector La Primavera',
    contactPhone: '318-662-9901',
    landmark: 'Frente al árbol de ceiba grande, portón negro',
    householdSize: 5,
    minorCount: 2,
    allDocumentsValid: true,
    allNNASchooled: true,
    hasDisabledMember: false,
    hasElderlyMember: true,
    elderlyCount: 1,
    rooms: 2,
    allEPSAffiliated: true,
    epsRegime: 'Subsidiado (Coosalud)',
    hasPregnantOrLactating: false,
    vaccinesUpToDate: true,
    vaccineCardAvailable: true,
    hasChronicDisease: true,
    chronicDiseaseDetails: 'Adulto mayor de 72 años con secuelas de ACV y artrosis severa',
    hasEDAParasites: false,
    dentalCarePending: true,
    healthcareAccessDifficulty: true,
    healthcareAccessDetails: 'Dificultad para trasladar al abuelo postrado para entrega de pañales y medicamentos',
    waterSource: 'ACUEDUCTO',
    psychologicalSupportNeeded: true,
    psychologicalSupportWho: 'Cuidadora principal con síndrome de agotamiento extremo (Burnout)',
    hasSTIHistoryOrSymptoms: false,
    lastPapSmear: 'MAS_3_ANOS',
    familyPlanningMethod: 'NINGUNO',
    desiresFamilyPlanningCounseling: true,
    vaginalInfectionSymptoms: false,
    breastSelfExamTrained: false,
    hasMammographyOrUltrasoundNeeded: true,
    hasFamilyProcess: false,
    hasVIFVBG: false,
    housingType: 'PROPIA',
    hasHousingDocument: false,
    hasDebtOrProcess: true,
    debtDetails: 'Crédito de droguería acumulado para insumos del paciente encamado',
    needsPensionOrSubsidy: true,
    pensionDetails: 'Requiere inclusión prioritaria en programa de cuidadores del Distrito',
    hasUrgentCase: false,
    incomeSource: 'Pensión mínima familiar y rifas de barrio',
    receivesSubsidies: true,
    subsidiesDetails: 'Colombia Mayor',
    hasJobSeeker: true,
    jobSearchDifficulty: 'Horario limitado por deber de cuidado permanente en casa',
    hasRecentGraduate: true,
    graduateStatus: 'Hija bachiller de 18 años sin recursos para ingresar al SENA o universidad',
    riskLevel: 'MEDIO',
    collectorObservations: 'Requiere visita domiciliaria de medicina interna, paquete de apoyo a cuidadores y citología.',
    activateImmediateRoute: false,
    needs: ['salud', 'cronica', 'citologia_urgente', 'subsidios', 'empleo'],
    priority: 'PRIORITARIA',
    householdMembers: [
      { fullName: 'Marta Luz Guerrero Polo', age: 48, relationship: 'Persona Referente / Cuidadora', documentType: 'CC', documentNumber: '45.890.123' },
      { fullName: 'Manuel Salvador Guerrero', age: 72, relationship: 'Padre (Postrado en cama)', documentType: 'CC', documentNumber: '9.123.456' },
      { fullName: 'Daniela Andrea Polo Guerrero', age: 18, relationship: 'Hija (Bachiller egresada)', documentType: 'CC', documentNumber: '1.047.990.112' },
      { fullName: 'Nicolás Polo Guerrero', age: 12, relationship: 'Hijo', documentType: 'TI', documentNumber: '1.144.332.119' },
      { fullName: 'Sofía Isabel Polo Guerrero', age: 9, relationship: 'Hija', documentType: 'TI', documentNumber: '1.144.901.223' },
    ]
  },
  {
    _id: 'demo-arz-006',
    surveyCode: 'CS-ARZ-006',
    barrio: 'Arroz Barato',
    manzana: 'Mz 11 Lote 09',
    visitDate: '2026-08-16T11:00:00.000Z',
    collectorName: 'Dra. Mileidys Romero',
    collectorCode: 'G-01',
    fieldZone: 'Sector La Laguna',
    contactPhone: '302-334-7711',
    landmark: 'Bajando por la trocha del pozo comunal',
    householdSize: 4,
    minorCount: 2,
    allDocumentsValid: true,
    allNNASchooled: true,
    hasDisabledMember: false,
    hasElderlyMember: false,
    rooms: 1,
    overcrowdingNotes: 'Vivienda precaria construida sobre palafitos de madera, riesgo de inundación',
    allEPSAffiliated: true,
    epsRegime: 'Subsidiado (Mutual Ser)',
    hasPregnantOrLactating: false,
    vaccinesUpToDate: false,
    vaccineCardAvailable: false,
    hasChronicDisease: false,
    hasEDAParasites: true,
    edaDetails: 'Niños con vómito y parásitos visibles por consumo de agua no hervida',
    dentalCarePending: true,
    healthcareAccessDifficulty: true,
    healthcareAccessDetails: 'Falta de dinero para pasajes en bus hacia el hospital de Blas de Lezo',
    waterSource: 'POZO',
    psychologicalSupportNeeded: false,
    hasSTIHistoryOrSymptoms: true,
    stiSymptomsDetails: 'Dispareunia intensa y secreciones blanquecinas recidivantes tratadas empíricamente',
    lastPapSmear: 'NUNCA',
    familyPlanningMethod: 'NINGUNO',
    desiresFamilyPlanningCounseling: true,
    vaginalInfectionSymptoms: true,
    breastSelfExamTrained: false,
    hasMammographyOrUltrasoundNeeded: false,
    hasFamilyProcess: true,
    familyProcessDetails: 'Agresiones físicas documentadas con lesiones visibles en rostro y brazos',
    hasVIFVBG: true,
    vifComplaintFiled: true,
    vifProcessStatus: 'Denuncia interpuesta en URI pero el agresor continúa merodeando la vivienda',
    housingType: 'OTRA',
    hasHousingDocument: false,
    hasDebtOrProcess: false,
    needsPensionOrSubsidy: false,
    hasUrgentCase: true,
    urgentCaseDescription: 'Víctima de violencia intrafamiliar con agresión física reciente + riesgo de feminicidio',
    incomeSource: 'Limpieza de casas particulares 2 días a la semana',
    receivesSubsidies: false,
    hasJobSeeker: true,
    jobSearchDifficulty: 'Víctima amenazada por el agresor para impedir que trabaje',
    hasRecentGraduate: false,
    riskLevel: 'ALTO',
    collectorObservations: 'ALERTA ROJA: Riesgo feminicida inminente. Se activa cuadrante policial y Casa de Refugio.',
    activateImmediateRoute: true,
    immediateRouteType: 'Medida de Protección Inmediata + Traslado Seguro Senda Mujer',
    needs: ['salud', 'violencia', 'familia', 'citologia_urgente', 'its_ginecologia', 'vivienda', 'empleo'],
    priority: 'INMEDIATA',
    householdMembers: [
      { fullName: 'Leidis Johana Carmona', age: 26, relationship: 'Persona Referente', documentType: 'CC', documentNumber: '1.047.662.339' },
      { fullName: 'Esteban Andrés Carmona', age: 6, relationship: 'Hijo', documentType: 'RC', documentNumber: '1.209.771.223' },
      { fullName: 'Lucía Milena Carmona', age: 4, relationship: 'Hija', documentType: 'RC', documentNumber: '1.288.990.114' },
      { fullName: 'Carmen Alicia Carmona', age: 49, relationship: 'Madre', documentType: 'CC', documentNumber: '33.456.789' },
    ]
  },
  {
    _id: 'demo-man-001',
    surveyCode: 'CS-MAN-001',
    barrio: 'Nelson Mandela',
    manzana: 'Sector Las Torres Mz 5',
    visitDate: '2026-08-17T09:00:00.000Z',
    collectorName: 'Dr. Hernán Silva',
    collectorCode: 'M-02',
    fieldZone: 'Sector Las Torres',
    contactPhone: '310-449-0012',
    landmark: 'Cerca a la torre de energía número 4',
    householdSize: 5,
    minorCount: 3,
    allDocumentsValid: true,
    allNNASchooled: true,
    hasDisabledMember: false,
    hasElderlyMember: false,
    rooms: 2,
    allEPSAffiliated: true,
    epsRegime: 'Subsidiado (Cajacopi)',
    hasPregnantOrLactating: true,
    prenatalCareStatus: 'Gestante adolescente de 17 años, 18 semanas de embarazo, primer hijo',
    vaccinesUpToDate: true,
    vaccineCardAvailable: true,
    hasChronicDisease: false,
    hasEDAParasites: false,
    dentalCarePending: true,
    healthcareAccessDifficulty: false,
    waterSource: 'CARROTANQUE',
    psychologicalSupportNeeded: true,
    psychologicalSupportWho: 'Gestante adolescente requiere asesoría en proyecto de vida y apoyo prenatal',
    hasSTIHistoryOrSymptoms: false,
    lastPapSmear: 'NO_APLICA',
    familyPlanningMethod: 'NINGUNO',
    desiresFamilyPlanningCounseling: true,
    vaginalInfectionSymptoms: false,
    breastSelfExamTrained: false,
    hasMammographyOrUltrasoundNeeded: false,
    hasFamilyProcess: false,
    hasVIFVBG: false,
    housingType: 'ARRENDADA',
    hasHousingDocument: false,
    hasDebtOrProcess: false,
    needsPensionOrSubsidy: true,
    pensionDetails: 'Solicita bono nutricional para gestantes y recién nacidos',
    hasUrgentCase: false,
    incomeSource: 'Albañilería y jornales de construcción',
    receivesSubsidies: false,
    hasJobSeeker: true,
    jobSearchDifficulty: 'Empleo informal inestable sujeto a temporadas de lluvia',
    hasRecentGraduate: false,
    riskLevel: 'MEDIO',
    collectorObservations: 'Embarazo adolescente prioritario para vinculación al programa nutricional y taller de lactancia.',
    activateImmediateRoute: false,
    needs: ['salud', 'materna', 'planificacion_familiar', 'subsidios'],
    priority: 'PRIORITARIA',
    householdMembers: [
      { fullName: 'Luz Marina Orozco', age: 39, relationship: 'Persona Referente', documentType: 'CC', documentNumber: '45.112.908' },
      { fullName: 'Jaime Luis Salcedo', age: 43, relationship: 'Cónyuge', documentType: 'CC', documentNumber: '9.887.654' },
      { fullName: 'Andrea Paola Salcedo Orozco', age: 17, relationship: 'Hija (Gestante 18 sem)', documentType: 'TI', documentNumber: '1.099.112.876' },
      { fullName: 'Santiago Salcedo Orozco', age: 11, relationship: 'Hijo', documentType: 'TI', documentNumber: '1.144.665.432' },
      { fullName: 'Mateo Salcedo Orozco', age: 5, relationship: 'Hijo', documentType: 'RC', documentNumber: '1.209.113.445' },
    ]
  },
  {
    _id: 'demo-man-002',
    surveyCode: 'CS-MAN-002',
    barrio: 'Nelson Mandela',
    manzana: 'Sector Primavera Mz 12',
    visitDate: '2026-08-17T11:15:00.000Z',
    collectorName: 'Dra. Vanessa Carvajal',
    collectorCode: 'J-03',
    fieldZone: 'Sector Primavera',
    contactPhone: '313-882-6655',
    landmark: 'Diagonal al comedor comunitario San Vicente',
    householdSize: 4,
    minorCount: 1,
    allDocumentsValid: true,
    allNNASchooled: true,
    hasDisabledMember: false,
    hasElderlyMember: true,
    elderlyCount: 1,
    rooms: 3,
    allEPSAffiliated: true,
    epsRegime: 'Subsidiado (Mutual Ser)',
    hasPregnantOrLactating: false,
    vaccinesUpToDate: true,
    vaccineCardAvailable: true,
    hasChronicDisease: true,
    chronicDiseaseDetails: 'Abuela de 78 años con hipertensión arterial y glaucoma diagnosticado',
    hasEDAParasites: false,
    dentalCarePending: true,
    healthcareAccessDifficulty: true,
    healthcareAccessDetails: 'Gotas oftalmológicas no suministradas por la droguería de la EPS desde hace 3 meses',
    waterSource: 'ACUEDUCTO',
    psychologicalSupportNeeded: false,
    hasSTIHistoryOrSymptoms: false,
    lastPapSmear: '1_A_3_ANOS',
    familyPlanningMethod: 'QUIRURGICO',
    desiresFamilyPlanningCounseling: false,
    vaginalInfectionSymptoms: false,
    breastSelfExamTrained: true,
    hasMammographyOrUltrasoundNeeded: true,
    hasFamilyProcess: false,
    hasVIFVBG: false,
    housingType: 'PROPIA',
    hasHousingDocument: true,
    hasDebtOrProcess: false,
    needsPensionOrSubsidy: true,
    pensionDetails: 'Trámite de Colombia Mayor pendiente de cupo en lista de espera',
    hasUrgentCase: false,
    incomeSource: 'Peluquería comunitaria en sala de la vivienda',
    receivesSubsidies: true,
    subsidiesDetails: 'Devolución del IVA',
    hasJobSeeker: false,
    hasRecentGraduate: false,
    riskLevel: 'BAJO',
    collectorObservations: 'Hogar cohesionado con emprendimiento propio. Se apoya tutela de salud por medicamentos de glaucoma.',
    activateImmediateRoute: false,
    needs: ['salud', 'cronica', 'acceso_salud', 'tramites'],
    priority: 'NORMAL',
    householdMembers: [
      { fullName: 'Sandra Patricia Miranda', age: 44, relationship: 'Persona Referente', documentType: 'CC', documentNumber: '45.667.112' },
      { fullName: 'Ana Joaquina Miranda de Ávila', age: 78, relationship: 'Madre', documentType: 'CC', documentNumber: '22.901.456' },
      { fullName: 'Jesús David Ávila Miranda', age: 21, relationship: 'Hijo (Estudiante SENA)', documentType: 'CC', documentNumber: '1.047.882.341' },
      { fullName: 'Mariana Ávila Miranda', age: 13, relationship: 'Hija', documentType: 'TI', documentNumber: '1.144.778.901' },
    ]
  }
];

export const DEMO_SURVEYS: any[] = RAW_DEMO_SURVEYS.map((s) => ({
  ...s,
  assignedPrograms: computeAssignedPrograms(s),
}));

