export type Program = {
  slug: string;
  number: string;
  title: string;
  focus: string;
  summary: string;
  image: string;
  imageAlt: string;
  actions: string[];
  route: string[];
  gallery: { src: string; alt: string; caption: string }[];
};

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=85`;
const gallery = (items: [string, string, string][]) => items.map(([id, alt, caption]) => ({ src: image(id), alt, caption }));

export const programs: Program[] = [
  { slug: 'mujer-acompanada', number: '01', title: 'Mujer Acompañada', focus: 'Atención social inicial', summary: 'Una primera escucha confidencial para comprender la situación, reconocer apoyos y construir un siguiente paso posible.', image: image('photo-1573496359142-b8d87734a5a2'), imageAlt: 'Profesional conversando durante una orientación', actions: ['Entrevista social confidencial y sin juzgamientos.', 'Valoración de necesidades y factores de vulnerabilidad.', 'Mapa de redes familiares, comunitarias e institucionales.', 'Plan de acompañamiento y seguimiento acordado con cada mujer.'], route: ['Escuchamos y comprendemos la situación.', 'Priorizamos necesidades y medidas de cuidado.', 'Conectamos con la ruta o el programa indicado.', 'Acompañamos el proceso y revisamos los siguientes pasos.'], gallery: gallery([['photo-1551836022-d5d88e9218df','Espacio de conversación','Espacios de escucha y orientación.'],['photo-1529156069898-49953e39b3ac','Grupo de mujeres reunidas','Redes que acompañan.'],['photo-1556761175-b413da4baf72','Reunión de trabajo','Construcción de un plan de acción.']]) },
  { slug: 'violencia-sexual', number: '02', title: 'Víctimas de Violencia Sexual', focus: 'Acompañamiento de caso', summary: 'Acompañamiento humano, reservado y centrado en derechos para que ninguna mujer enfrente sola los servicios de salud o justicia.', image: image('photo-1544027993-37dbfe43562a'), imageAlt: 'Manos unidas como símbolo de acompañamiento', actions: ['Orientación sobre atención en salud y activación de rutas.', 'Contención emocional en momentos de crisis.', 'Información clara para ejercer derechos sin presiones.', 'Acompañamiento ante instituciones cuando la mujer lo solicita.'], route: ['Atención segura y escucha inicial.', 'Identificación de necesidades urgentes de salud y protección.', 'Activación informada de la ruta institucional.', 'Seguimiento respetando el ritmo y las decisiones de la mujer.'], gallery: gallery([['photo-1529156069898-49953e39b3ac','Círculo de apoyo','Redes de apoyo y escucha.'],['photo-1556761175-b413da4baf72','Equipo en una mesa','Articulación para el acompañamiento.'],['photo-1551836022-d5d88e9218df','Conversación privada','Orientación en un espacio de confianza.']]) },
  { slug: 'contencion-psicosocial', number: '03', title: 'Contención Psicosocial', focus: 'Salud mental y emocional', summary: 'Espacios individuales y colectivos para cuidar la salud emocional, fortalecer recursos personales y volver a tejer redes.', image: image('photo-1529156069898-49953e39b3ac'), imageAlt: 'Mujeres reunidas en un círculo de apoyo', actions: ['Primeros auxilios psicológicos y orientación.', 'Espacios individuales de acompañamiento.', 'Círculos de palabra y apoyo mutuo.', 'Herramientas para la gestión emocional y el autocuidado.'], route: ['Reconocemos cómo te sientes hoy.', 'Definimos el tipo de apoyo más oportuno.', 'Acompañamos de forma individual o grupal.', 'Fortalecemos recursos para continuar tu proceso.'], gallery: gallery([['photo-1529156069898-49953e39b3ac','Círculo de conversación','Círculos de palabra.'],['photo-1542744173-8e7e53415bb0','Personas conversando','Acompañamiento cercano.'],['photo-1551836022-d5d88e9218df','Reunión de orientación','Construcción de redes de apoyo.']]) },
  { slug: 'salud-y-derechos', number: '04', title: 'Ruta de Salud y Derechos', focus: 'Salud sexual y reproductiva', summary: 'Orientación para acceder de forma oportuna, informada, segura y confidencial a servicios de salud y al ejercicio de derechos.', image: image('photo-1559757175-0eb30cd8c063'), imageAlt: 'Profesional de salud atendiendo a una paciente', actions: ['Orientación en salud sexual y reproductiva.', 'Información sobre derechos y consentimiento informado.', 'Articulación con redes de salud y servicios aliados.', 'Acompañamiento ante barreras de acceso cuando se requiera.'], route: ['Escuchamos la necesidad de salud.', 'Compartimos información clara y basada en derechos.', 'Identificamos servicios disponibles y opciones.', 'Acompañamos la conexión con la atención.'], gallery: gallery([['photo-1576091160399-112ba8d25d1d','Jornada de salud','Jornadas de cuidado en territorio.'],['photo-1559757175-0eb30cd8c063','Atención médica','Orientación para acceder a servicios.'],['photo-1505751172876-fa1923c5c528','Consulta de salud','Cuidado oportuno y digno.']]) },
  { slug: 'embarazo-con-apoyo', number: '05', title: 'Embarazo con Apoyo', focus: 'Maternidad elegida', summary: 'Acompañamiento integral para quienes deciden continuar su embarazo, con información, cuidado y una red que sostiene.', image: image('photo-1555252333-9f8e92e65df9'), imageAlt: 'Mujer gestante acompañada', actions: ['Orientación en controles prenatales y señales de alerta.', 'Información para decisiones libres e informadas.', 'Apoyo nutricional y conexión con redes de cuidado.', 'Preparación para parto, lactancia y puerperio.'], route: ['Conversamos sobre necesidades y expectativas.', 'Conectamos con controles y servicios de salud.', 'Fortalecemos la red de cuidado.', 'Acompañamos la etapa prenatal y posterior al parto.'], gallery: gallery([['photo-1555252333-9f8e92e65df9','Mujer embarazada','Acompañamiento en una etapa decisiva.'],['photo-1505751172876-fa1923c5c528','Atención de salud','Conexión con el cuidado en salud.'],['photo-1529156069898-49953e39b3ac','Mujeres reunidas','Redes que cuidan.']]) },
  { slug: 'mujer-y-justicia', number: '06', title: 'Mujer y Justicia', focus: 'Orientación jurídica con enfoque de género', summary: 'Información jurídica comprensible y acompañamiento para que las mujeres puedan reconocer, ejercer y exigir sus derechos.', image: image('photo-1450101499163-c8848c66ca85'), imageAlt: 'Documentos y orientación jurídica', actions: ['Orientación sobre violencia basada en género y medidas de protección.', 'Información sobre alimentos, custodia, tutelas y derechos de familia.', 'Preparación para trámites y conexión con redes jurídicas aliadas.', 'Acompañamiento que previene la revictimización.'], route: ['Escuchamos los hechos y la necesidad jurídica.', 'Explicamos opciones y alcances en lenguaje claro.', 'Definimos la ruta con consentimiento informado.', 'Acompañamos el acceso a la institución competente.'], gallery: gallery([['photo-1450101499163-c8848c66ca85','Documentos legales','Información jurídica clara.'],['photo-1551836022-d5d88e9218df','Orientación profesional','Orientación y preparación de la ruta.'],['photo-1556761175-b413da4baf72','Reunión de equipo','Redes de apoyo para el acceso a derechos.']]) },
  { slug: 'proyecto-de-vida-y-autonomia', number: '07', title: 'Proyecto de Vida y Autonomía', focus: 'Autonomía económica', summary: 'Formación y oportunidades productivas para fortalecer la autonomía económica, la confianza y el proyecto de vida de cada mujer.', image: image('photo-1556761175-b413da4baf72'), imageAlt: 'Mujeres trabajando en formación', actions: ['Orientación vocacional y construcción de proyecto de vida.', 'Formación técnica, financiera y comercial.', 'Acceso a herramientas, espacios y redes de apoyo.', 'Acompañamiento a emprendimientos y oportunidades de ingreso.'], route: ['Reconocemos intereses, saberes y metas.', 'Elegimos una línea de formación o producción.', 'Fortalecemos habilidades técnicas y comerciales.', 'Acompañamos la sostenibilidad y la autonomía.'], gallery: gallery([['photo-1556761175-b413da4baf72','Mujeres en formación','Aprendizaje y organización.'],['photo-1497215728101-856f4ea42174','Espacio de trabajo','Herramientas para emprender.'],['photo-1529156069898-49953e39b3ac','Grupo de mujeres','Comunidad y autonomía.']]) },
];
export const getProgram = (slug: string) => programs.find((program) => program.slug === slug);
