import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, Scale } from 'lucide-react';

const cam = ['Escucha y valoración inicial', 'Definición conjunta de prioridades', 'Activación de redes y servicios', 'Seguimiento con enfoque de autonomía'];
const themis = ['Información jurídica comprensible', 'Decisiones libres e informadas', 'No revictimización y confidencialidad', 'Articulación con rutas competentes'];

export default function ModelosPage() { return <div className="bg-[#fbf8f3]"><section className="border-b border-[#ddd4ca] bg-[#f4eee7] py-16 sm:py-24"><div className="senda-shell max-w-4xl"><p className="senda-eyebrow">Cómo acompañamos</p><h1 className="mt-3 font-serif text-5xl font-semibold leading-[.95] tracking-tight text-[#26231f] sm:text-7xl">Modelos que convierten la orientación en una ruta clara.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#6c665f]">CAM y THEMIS organizan el acompañamiento de la Fundación: uno integra la atención y el otro guía el acceso a derechos y justicia.</p></div></section><Model id="cam" icon={<BriefcaseBusiness className="h-9 w-9 text-[#6e3f58]"/>} label="Modelo CAM" title="Acompañamiento integral y coordinado." text="CAM organiza la escucha, la orientación, la conexión con servicios y el seguimiento. Su propósito es que cada mujer encuentre una respuesta comprensible, segura y acorde con sus decisiones." steps={cam}/><Model id="themis" dark icon={<Scale className="h-9 w-9 text-[#d9b991]"/>} label="Modelo THEMIS" title="Orientación jurídica con enfoque de género y derechos." text="THEMIS guía la orientación jurídica para que la información sea clara, las opciones se expliquen sin presiones y el acceso a la justicia no produzca nuevas formas de daño." steps={themis}/><section className="senda-section"><div className="senda-shell flex flex-col justify-between gap-6 rounded-3xl bg-[#f0e1da] p-8 sm:flex-row sm:items-center"><div><p className="senda-eyebrow">Conoce las rutas</p><h2 className="mt-2 font-serif text-3xl font-semibold text-[#26231f]">Los modelos se viven a través de nuestros programas.</h2></div><Link href="/programas" className="senda-button senda-button--primary">Ver programas <ArrowRight/></Link></div></section></div>; }

function Model({ id, icon, label, title, text, steps, dark = false }: { id:string; icon:React.ReactNode; label:string; title:string; text:string; steps:string[]; dark?:boolean }) { const colors = dark ? 'bg-[#203c3d] text-white' : 'text-[#26231f]'; const textColor = dark ? 'text-[#d6e7e1]' : 'text-[#6c665f]'; const card = dark ? 'border-white/15 bg-white/5' : 'border-[#ddd4ca] bg-[#fffdf9]'; const accent = dark ? 'text-[#d9b991]' : 'text-[#6e3f58]'; return <section id={id} className={`scroll-mt-32 py-16 sm:py-24 ${colors}`}><div className="senda-shell grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div>{icon}<p className={`mt-6 text-xs font-bold uppercase tracking-[.15em] ${accent}`}>{label}</p><h2 className="mt-3 font-serif text-4xl font-semibold">{title}</h2></div><div className={`space-y-5 text-sm leading-7 ${textColor}`}><p>{text}</p><div className="grid gap-3 sm:grid-cols-2">{steps.map((item, i) => <div key={item} className={`rounded-2xl border p-5 ${card}`}><span className={`text-xs font-bold ${accent}`}>0{i + 1}</span><p className={`mt-5 font-semibold ${dark ? 'text-white' : 'text-[#26231f]'}`}>{item}</p></div>)}</div></div></div></section>; }
