import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import DoctorProfile from '@/lib/models/DoctorProfile';
import PatientEHR from '@/lib/models/PatientEHR';

const INITIAL_PROFESSIONALS = [
  {
    id: 'PROF-ADMIN',
    name: 'Dra. Sorelvis Murillo (Administración)',
    role: 'ADMIN_SISTEMA',
    roleTitle: 'Directora Ejecutiva & Administradora del Sistema',
    specialty: 'Gestión Global, Creación de Médicos, Citas & Pacientes',
    code: 'ADMIN-001',
    rethus: 'DIR-EJECUTIVA-2026',
    email: 'admin.senda@sendamujer.org',
    phone: '+57 301 469 2095',
    avatarBg: 'bg-amber-600',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300',
    status: 'ACTIVO',
  },
  {
    id: 'PROF-101',
    name: 'Dra. Elena Ruiz',
    role: 'MEDICO',
    roleTitle: 'Médica Especialista en Ginecología & Obstetricia',
    specialty: 'Salud Reproductiva & Ecografía Pélvica',
    code: 'MED-7712',
    rethus: 'RETHUS 1047892-BOL',
    email: 'elena.ruiz@sendamujer.org',
    phone: '+57 300 112 4490',
    avatarBg: 'bg-emerald-600',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    status: 'ACTIVO',
  },
  {
    id: 'PROF-102',
    name: 'Lic. Sorelvis Murillo',
    role: 'TRABAJO_SOCIAL',
    roleTitle: 'Trabajadora Social de Territorio',
    specialty: 'Acompañamiento Domiciliario & Proyectos',
    code: 'SOC-4401',
    rethus: 'RETHUS 99281-TS-COL',
    email: 'sorelvis.murillo@sendamujer.org',
    phone: '+57 301 469 2095',
    avatarBg: 'bg-purple-600',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-300',
    status: 'ACTIVO',
  },
  {
    id: 'PROF-103',
    name: 'Dra. Patricia Herrera',
    role: 'JURIDICO',
    roleTitle: 'Abogada Especialista en VBG & Ley 1257 de 2008',
    specialty: 'Derecho de Familia & Medidas de Protección',
    code: 'JUR-9923',
    rethus: 'TP 204918-CSJ',
    email: 'patricia.herrera@sendamujer.org',
    phone: '+57 315 889 0011',
    avatarBg: 'bg-blue-600',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
    status: 'ACTIVO',
  },
  {
    id: 'PROF-104',
    name: 'Lic. Claudia Morales',
    role: 'PSICOLOGO',
    roleTitle: 'Psicóloga Clínica & Salud Mental',
    specialty: 'Contención Emocional & Trauma de Género',
    code: 'PSI-3320',
    rethus: 'COLPSIC 449102-PSI',
    email: 'claudia.morales@sendamujer.org',
    phone: '+57 312 443 8810',
    avatarBg: 'bg-pink-600',
    badgeColor: 'bg-pink-100 text-pink-800 border-pink-300',
    status: 'ACTIVO',
  },
];

const INITIAL_PATIENTS_EHR = [
  {
    id: 'EHR-001',
    patientCode: 'CSM-2026-000481',
    patientName: 'María Alejandra Torres',
    docId: '1.047.892.411',
    age: 28,
    birthDate: '1998-04-14',
    bloodType: 'O+',
    eps: 'Mutual Ser EPS-S',
    phone: '+57 300 489 1120',
    emergencyContact: 'Carmen Torres (Madre) - +57 301 223 9901',
    neighborhood: 'Pie de la Popa, Calle 30 #21-45, Cartagena',
    allergies: 'Penicilina, Sulfas',
    riskLevel: 'BAJO',
    ipscScore: 78,
    dimensionsIPSC: { seguridadFisica: 8, seguridadDigital: 7, autonomiaEconomica: 8, redDeApoyo: 8, accesoAJusticia: 8, accesoASalud: 8, bienestarPsicosocial: 8, conocimientoDerechos: 8, capacidadRespuesta: 7, continuidadAcompanamiento: 8 },
    primaryCategory: 'MEDICO',
    assignedDoctor: 'Dra. Elena Ruiz',
    status: 'RUTA_ACTIVADA',
    vitals: { bloodPressure: '120/80 mmHg', heartRate: 74, weightKg: 62, heightM: 1.62, bmi: 23.6, tempC: 36.6 },
    evolutions: [
      {
        id: 'EVO-101',
        date: '2026-09-01',
        time: '09:30 AM',
        author: 'Dra. Elena Ruiz',
        role: 'MEDICO',
        rethus: 'RETHUS 1047892-BOL',
        subjective: 'Paciente gestante de 14 semanas en control prenatal.',
        objective: 'AU: 12 cm. FCF: 148 lpm audible con Doppler.',
        analysis: 'Supervisión de embarazo normal de 14 semanas. CIE-10: Z34.8.',
        plan: '1. Ácido Fólico + Sulfato Ferroso. 2. Ecografía Morfológica.',
        cie10Code: 'Z34.8',
      },
    ],
    prescriptions: [{ id: 'RX-1', date: '2026-09-01', medication: 'Ácido Fólico 1mg Tab', dosage: '1 tableta VO cada 24 horas', duration: '90 días', doctor: 'Dra. Elena Ruiz' }],
    routesActivated: [{ routeName: 'Atención Médica Prenatal Preferencial', date: '2026-08-15', status: 'COMPLETADA', entity: 'Sede Cartagena Senda Mujer' }],
    documents: [{ name: 'Ecografía_Obstétrica_14S.pdf', date: '2026-09-01', category: 'Ecografía' }],
  },
  {
    id: 'EHR-002',
    patientCode: 'CSM-2026-000482',
    patientName: 'Valeria Castro',
    docId: '1.050.441.982',
    age: 32,
    birthDate: '1994-11-02',
    bloodType: 'A+',
    eps: 'Coosalud EPS',
    phone: '+57 312 901 8843',
    emergencyContact: 'Sofía Castro (Hermana) - +57 310 994 0012',
    neighborhood: 'Chiquinquirá, Transversal 54 #30-12, Cartagena',
    allergies: 'Ninguna conocida',
    riskLevel: 'ALTO',
    ipscScore: 42,
    dimensionsIPSC: { seguridadFisica: 3, seguridadDigital: 4, autonomiaEconomica: 4, redDeApoyo: 5, accesoAJusticia: 4, accesoASalud: 5, bienestarPsicosocial: 4, conocimientoDerechos: 5, capacidadRespuesta: 4, continuidadAcompanamiento: 4 },
    primaryCategory: 'JURIDICO',
    assignedDoctor: 'Dra. Patricia Herrera',
    status: 'EN_ORIENTACION',
    vitals: { bloodPressure: '135/85 mmHg', heartRate: 88, weightKg: 58, heightM: 1.58, bmi: 23.2, tempC: 36.5 },
    evolutions: [
      {
        id: 'EVO-201',
        date: '2026-08-30',
        time: '11:00 AM',
        author: 'Dra. Patricia Herrera',
        role: 'JURIDICO',
        rethus: 'TP 204918-CSJ',
        subjective: 'Solicitud de asesoría por violencia intrafamiliar y perturbación psicológica.',
        objective: 'Radicación de Medidas de Protección Ley 1257 ante Comisaría Chiquinquirá.',
        analysis: 'Vulnerabilidad jurídica que requiere medida cautelar urgente.',
        plan: '1. Medida de Protección Prioritaria. 2. Alarma activa Patrulla Púrpura.',
        cie10Code: 'Z65.9',
      },
    ],
    prescriptions: [],
    routesActivated: [{ routeName: 'Medida de Protección Ley 1257 de 2008', date: '2026-08-30', status: 'ACTIVADA', entity: 'Comisaría de Familia Chiquinquirá' }],
    documents: [{ name: 'Copia_Denuncia_Comisaria.pdf', date: '2026-08-30', category: 'Denuncia Legal' }],
  },
  {
    id: 'EHR-003',
    patientCode: 'CSM-2026-000483',
    patientName: 'Carolina Mendoza',
    docId: '1.143.902.118',
    age: 35,
    birthDate: '1991-07-22',
    bloodType: 'O+',
    eps: 'Cajacopi EPS',
    phone: '+57 301 554 9901',
    emergencyContact: 'Pedro Mendoza (Padre) - +57 300 881 7722',
    neighborhood: 'Olaya Herrera, Sector Central, Cartagena',
    allergies: 'Dipirona',
    riskLevel: 'BAJO',
    ipscScore: 74,
    dimensionsIPSC: { seguridadFisica: 7, seguridadDigital: 7, autonomiaEconomica: 8, redDeApoyo: 7, accesoAJusticia: 7, accesoASalud: 8, bienestarPsicosocial: 7, conocimientoDerechos: 8, capacidadRespuesta: 7, continuidadAcompanamiento: 8 },
    primaryCategory: 'TRABAJO_SOCIAL',
    assignedDoctor: 'Lic. Sorelvis Murillo',
    status: 'EN_SEGUIMIENTO',
    vitals: { bloodPressure: '118/75 mmHg', heartRate: 70, weightKg: 65, heightM: 1.65, bmi: 23.8, tempC: 36.4 },
    evolutions: [
      {
        id: 'EVO-301',
        date: '2026-08-28',
        time: '04:00 PM',
        author: 'Lic. Sorelvis Murillo',
        role: 'TRABAJO_SOCIAL',
        rethus: 'RETHUS 99281-TS-COL',
        subjective: 'Seguimiento de micronegocio taller textil Olaya Herrera.',
        objective: '140 prendas confeccionadas y ventas de $1.250.000 COP.',
        analysis: 'Alto grado de autonomía económica alcanzado.',
        plan: '1. Participación en Feria Senda. 2. Cita en 30 días.',
      },
    ],
    prescriptions: [],
    routesActivated: [{ routeName: 'Capacitación WhatsApp Business SendaAcademia', date: '2026-08-10', status: 'COMPLETADA', entity: 'SendaAcademia' }],
    documents: [],
  },
  {
    id: 'EHR-004',
    patientCode: 'CSM-2026-000484',
    patientName: 'Diana Marcela Gómez',
    docId: '1.048.223.109',
    age: 29,
    birthDate: '1997-03-12',
    bloodType: 'A-',
    eps: 'Mutual Ser EPS-S',
    phone: '+57 318 765 4321',
    emergencyContact: 'Marta Gómez (Hermana) - +57 318 009 2211',
    neighborhood: 'El Pozón, Sector 20 de Enero, Cartagena',
    allergies: 'Ninguna',
    riskLevel: 'MODERADO',
    ipscScore: 51,
    dimensionsIPSC: { seguridadFisica: 5, seguridadDigital: 5, autonomiaEconomica: 4, redDeApoyo: 6, accesoAJusticia: 5, accesoASalud: 6, bienestarPsicosocial: 5, conocimientoDerechos: 5, capacidadRespuesta: 5, continuidadAcompanamiento: 5 },
    primaryCategory: 'PSICOLOGO',
    assignedDoctor: 'Lic. Claudia Morales',
    status: 'EN_ORIENTACION',
    vitals: { bloodPressure: '122/82 mmHg', heartRate: 78, weightKg: 59, heightM: 1.61, bmi: 22.8, tempC: 36.6 },
    evolutions: [
      {
        id: 'EVO-401',
        date: '2026-08-29',
        time: '10:00 AM',
        author: 'Lic. Claudia Morales',
        role: 'PSICOLOGO',
        rethus: 'COLPSIC 449102-PSI',
        subjective: 'Consulta psicosocial inicial por síntomas de ansiedad moderada.',
        objective: 'Triaje completado. Red de apoyo familiar parcial presente.',
        analysis: 'Estrés agudo reactivo. Requiere fortalecimiento psicosocial.',
        plan: '1. Sesiones semanales de psicología. 2. Taller SendaAcademia.',
      },
    ],
    prescriptions: [],
    routesActivated: [],
    documents: [],
  },
  {
    id: 'EHR-005',
    patientCode: 'SENDA-A3F1C2',
    patientName: 'Sorelvis Murillo (Demo Beneficiaria)',
    docId: '45.789.012',
    age: 40,
    birthDate: '1986-09-08',
    bloodType: 'O+',
    eps: 'Coosalud EPS',
    phone: '+57 301 469 2095',
    emergencyContact: 'Fundación Senda Mujer - Cartagena',
    neighborhood: 'Nelson Mandela, Sector 1, Cartagena',
    allergies: 'Ninguna',
    riskLevel: 'BAJO',
    ipscScore: 85,
    dimensionsIPSC: { seguridadFisica: 9, seguridadDigital: 8, autonomiaEconomica: 9, redDeApoyo: 9, accesoAJusticia: 8, accesoASalud: 9, bienestarPsicosocial: 8, conocimientoDerechos: 9, capacidadRespuesta: 8, continuidadAcompanamiento: 9 },
    primaryCategory: 'TRABAJO_SOCIAL',
    assignedDoctor: 'Lic. Sorelvis Murillo',
    status: 'COMPLETADA',
    vitals: { bloodPressure: '115/75 mmHg', heartRate: 68, weightKg: 64, heightM: 1.63, bmi: 24.1, tempC: 36.5 },
    evolutions: [
      {
        id: 'EVO-501',
        date: '2026-08-25',
        time: '03:00 PM',
        author: 'Lic. Sorelvis Murillo',
        role: 'TRABAJO_SOCIAL',
        rethus: 'RETHUS 99281-TS-COL',
        subjective: 'Evaluación final del ciclo de autonomía económica y liderazgo.',
        objective: 'Graduada de SendaAcademia con 100% de cumplimiento.',
        analysis: 'Autonomía y fortalecimiento integral destacado.',
        plan: '1. Vinculación como lideresa mentora comunitaria.',
      },
    ],
    prescriptions: [],
    routesActivated: [{ routeName: 'Certificación Liderazgo Comunitario', date: '2026-08-25', status: 'COMPLETADA', entity: 'Fundación Senda Mujer' }],
    documents: [],
  },
];

export async function POST() {
  try {
    await connectToDatabase();

    await DoctorProfile.deleteMany({});
    await DoctorProfile.insertMany(INITIAL_PROFESSIONALS);

    await PatientEHR.deleteMany({});
    await PatientEHR.insertMany(INITIAL_PATIENTS_EHR);

    return NextResponse.json({
      success: true,
      message: 'Base de datos MongoDB de la Fundación Senda re-inicializada con éxito.',
      doctorsCount: INITIAL_PROFESSIONALS.length,
      patientsCount: INITIAL_PATIENTS_EHR.length,
    });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
