import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, HeartHandshake, MessageCircle, Scale, ShieldCheck, Stethoscope } from 'lucide-react';
import HeroSection from '@/components/HeroSection';

const needs = [
  { icon: ShieldCheck, title: 'Estoy viviendo violencia', text: 'Orientación, protección y rutas.', href: '/triaje-psicologico' },
  { icon: MessageCircle, title: 'Necesito hablar con alguien', text: 'Escucha y contención emocional.', href: '/triaje-psicologico' },
  { icon: Scale, title: 'Necesito orientación jurídica', text: 'Derechos y acompañamiento legal.', href: '/agendar-cita?especialidad=Asesor%C3%ADa%20Jur%C3%ADdica' },
  { icon: Stethoscope, title: 'Necesito atención en salud', text: 'Orientación médica y social.', href: '/agendar-cita' },
];

const programs = [
  ['01', 'Mujer Acompañada', 'Primera escucha y orientación social.'],
  ['02', 'Violencia Sexual', 'Protección, salud y acompañamiento de caso.'],
  ['03', 'Contención Psicosocial', 'Salud mental, duelo y redes de apoyo.'],
  ['04', 'Salud y Derechos', 'Atención médica, social y jurídica.'],
  ['05', 'Embarazo con Apoyo', 'Acompañamiento durante una etapa decisiva.'],
  ['06', 'Mujer y Justicia', 'Orientación legal para ejercer derechos.'],
  ['07', 'Proyecto de Vida', 'Educación, autonomía y oportunidades.'],
];

const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'NGO',
  name: 'Fundación Senda Mujer',
  url: 'https://fundacionsendamujer.vercel.app/',
  logo: 'https://fundacionsendamujer.vercel.app/logo.png',
  description: 'Acompañamiento gratuito, confidencial e integral para mujeres y niñas en Cartagena.',
  areaServed: ['Cartagena de Indias', 'Bolívar', 'Colombia'],
  telephone: '+57 301 469 2095',
};

export default function HomePage() {
  return (
    <div className="bg-[#FCF9F6] pb-20 font-sans" itemScope itemType="https://schema.org/NGO">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />

      <HeroSection />

      <section id="necesidades" className="mx-auto max-w-7xl px-6 py-14 sm:py-20 lg:px-8" aria-labelledby="needs-title">
        <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
          <div><p className="text-[11px] font-black uppercase tracking-[.16em] text-senda-pink">Empieza por aquí</p><h2 id="needs-title" className="mt-2 text-3xl font-black tracking-tight text-senda-purple-dark sm:text-5xl">¿Qué necesitas hoy?</h2></div>
          <p className="max-w-md text-sm leading-relaxed text-slate-600">No tienes que conocer las instituciones ni las palabras correctas. Elige una opción y te mostramos el siguiente paso.</p>
        </div>
        <div className="mt-8 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {needs.map(({ icon: Icon, title, text, href }) => <Link key={title} href={href} className="group rounded-2xl border border-[#e4d7ce] bg-white p-5 transition-all hover:-translate-y-1 hover:shadow-xl"><Icon className="h-5 w-5 text-senda-pink" /><h3 className="mt-7 text-sm font-black text-slate-800">{title}</h3><p className="mt-1 text-xs text-slate-500">{text}</p><ArrowRight className="mt-5 h-4 w-4 text-senda-pink transition-transform group-hover:translate-x-1" /></Link>)}
        </div>
      </section>

      <section id="acompanamos" className="border-y border-[#e6dcd4] bg-white" aria-labelledby="path-title">
        <div className="mx-auto max-w-7xl px-6 py-14 sm:py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-senda-pink">Nuestro modelo</p><h2 id="path-title" className="mt-2 text-3xl font-black tracking-tight text-senda-purple-dark sm:text-5xl">Tu camino con Senda</h2></div><p className="max-w-md text-sm leading-relaxed text-slate-600">Un acompañamiento claro, humano y continuo.</p></div><ol className="mt-10 grid grid-cols-1 border-t border-[#e6dcd4] sm:grid-cols-2 lg:grid-cols-4">{[['01', 'Escuchamos', 'Entendemos tu situación sin juzgar.'], ['02', 'Orientamos', 'Identificamos necesidades y prioridades.'], ['03', 'Activamos tu ruta', 'Conectamos la ayuda profesional.'], ['04', 'Acompañamos', 'Damos continuidad y fortalecemos autonomía.']].map(([n, title, desc]) => <li key={n} className="min-h-40 border-b border-[#e6dcd4] py-6 pr-6 last:border-0 sm:odd:pr-8 lg:border-b-0 lg:border-r lg:pl-6 lg:first:pl-0 lg:last:border-0"><span className="inline-grid h-8 w-8 place-items-center rounded-full border border-[#d9c8bd] text-[10px] font-black text-senda-pink">{n}</span><h3 className="mt-5 font-black text-slate-800">{title}</h3><p className="mt-2 max-w-[210px] text-xs leading-relaxed text-slate-500">{desc}</p></li>)}</ol></div>
      </section>

      <section id="senda-caribe" className="mx-auto max-w-7xl px-6 py-14 sm:py-20 lg:px-8" aria-labelledby="caribe-title"><div className="overflow-hidden rounded-[2rem] bg-[#203C3D] p-7 text-white shadow-xl sm:p-12"><div className="grid items-center gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-[#D9B991]">Senda Caribe</p><h2 id="caribe-title" className="mt-3 max-w-xl text-4xl font-black leading-[1.02] tracking-tight sm:text-6xl">Protección cercana para un Caribe más seguro.</h2><p className="mt-5 max-w-xl text-sm leading-relaxed text-emerald-50/80">Prevención, rutas de atención, acompañamiento profesional y evidencia territorial en un solo ecosistema.</p><Link href="/caribe-seguro" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#D9B991] px-6 py-3.5 text-xs font-black text-[#203C3D] transition-colors hover:bg-[#EED3AD]">Conocer Senda Caribe <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-3xl border border-white/20 bg-white/10 p-5 backdrop-blur-sm"><div className="flex items-center gap-3 border-b border-white/15 pb-5"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#D9B991] text-xs font-black text-[#203C3D]">SC</span><div><strong className="block text-sm">Centro de acompañamiento</strong><span className="text-[11px] text-emerald-50/70">Tu ruta, en un solo lugar</span></div></div><div className="space-y-3 pt-5">{[['Encontrar una ruta', '/caribe-seguro/rutas'], ['Mi plan de protección', '/caribe-seguro/proteccion'], ['Red profesional', '/caribe-seguro/red']].map(([label, href]) => <Link key={href} href={href} className="flex items-center justify-between rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-xs font-bold transition-colors hover:bg-white/10"><span>{label}</span><ArrowRight className="h-4 w-4 text-[#D9B991]" /></Link>)}</div></div></div></div></section>

      <section id="ruta" className="bg-[#F7F1EB]" aria-labelledby="rights-title"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-14 sm:py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-senda-pink">Herramienta de derechos</p><h2 id="rights-title" className="mt-2 text-4xl font-black leading-[1.02] tracking-tight text-senda-purple-dark sm:text-6xl">Conoce tus derechos y encuentra tu ruta.</h2><p className="mt-5 max-w-lg text-sm leading-relaxed text-slate-600">SENDA Universal te orienta con preguntas claras sobre salud, protección, derechos y servicios disponibles.</p><Link href="/senda-universal" className="mt-7 inline-flex items-center gap-2 rounded-full bg-senda-purple px-6 py-3.5 text-xs font-black text-white transition-colors hover:bg-senda-purple-dark">Comenzar orientación <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-3xl border border-[#e1d5ca] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center justify-between text-[10px] font-black uppercase tracking-widest text-slate-400"><span>Orientación gratuita</span><span className="text-senda-pink">Paso 1 de 5</span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#eee4dc]"><span className="block h-full w-1/5 rounded-full bg-senda-pink" /></div><h3 className="mt-8 text-2xl font-black text-senda-purple-dark">¿Qué necesitas hoy?</h3><div className="mt-5 divide-y divide-[#eee4dc] text-sm text-slate-600"><div className="flex gap-3 py-4"><b className="text-senda-pink">01</b><span>Conozcamos tu situación</span></div><div className="flex gap-3 py-4 text-slate-400"><b>02</b><span>Identifiquemos opciones</span></div></div></div></div></section>

      <section id="programas" className="mx-auto max-w-7xl px-6 py-14 sm:py-20 lg:px-8" aria-labelledby="programs-title"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-senda-pink">Cómo ayudamos</p><h2 id="programs-title" className="mt-2 text-3xl font-black tracking-tight text-senda-purple-dark sm:text-5xl">Programas para situaciones reales.</h2></div><Link href="/programas" className="inline-flex items-center gap-2 text-xs font-black text-senda-pink">Ver todos los programas <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-8 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{programs.map(([n, title, desc]) => <Link key={n} href={`/programas#programa-${n}`} className="group min-h-44 rounded-2xl border border-[#e4d7ce] bg-white p-5 transition-all hover:-translate-y-1 hover:shadow-lg"><span className="text-[10px] font-black text-senda-pink">{n}</span><h3 className="mt-10 text-lg font-black leading-tight text-senda-purple-dark">{title}</h3><p className="mt-2 text-xs leading-relaxed text-slate-500">{desc}</p><ArrowRight className="mt-4 h-4 w-4 text-senda-pink transition-transform group-hover:translate-x-1" /></Link>)}</div></section>

      <section id="historias" className="bg-[#F7F1EB]" aria-labelledby="stories-title"><div className="mx-auto max-w-7xl px-6 py-14 sm:py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-senda-pink">Historias de impacto</p><h2 id="stories-title" className="mt-2 text-3xl font-black tracking-tight text-senda-purple-dark sm:text-5xl">Lo que pasa cuando alguien acompaña.</h2></div><Link href="/galeria" className="inline-flex items-center gap-2 text-xs font-black text-senda-pink">Ver galería completa <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-[1.35fr_.65fr] md:grid-rows-2"><Link href="/galeria" className="group relative min-h-[360px] overflow-hidden rounded-3xl bg-slate-900 md:row-span-2"><Image src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=85" alt="Jornada de salud y acompañamiento en Cartagena" fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 60vw" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/85 via-slate-950/10 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-white"><span className="text-[10px] font-black uppercase tracking-[.14em] text-[#D9B991]">Arroz Barato · Cartagena</span><h3 className="mt-2 max-w-lg text-2xl font-black leading-tight">Una jornada de salud puede abrir una ruta de cuidado.</h3><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#D9B991]">Leer historia <ArrowRight className="h-4 w-4" /></span></div></Link><Link href="/galeria" className="group relative min-h-[170px] overflow-hidden rounded-3xl bg-slate-900"><Image src="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=85" alt="Círculo de apoyo psicosocial" fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 30vw" /><div className="absolute inset-0 bg-slate-950/45" /><span className="absolute bottom-5 left-5 text-sm font-black text-white">Escuchar también es proteger <ArrowRight className="ml-2 inline h-4 w-4 text-[#D9B991]" /></span></Link><Link href="/galeria" className="group relative min-h-[170px] overflow-hidden rounded-3xl bg-slate-900"><Image src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=800&q=85" alt="Mujeres en formación y autonomía económica" fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 30vw" /><div className="absolute inset-0 bg-slate-950/45" /><span className="absolute bottom-5 left-5 text-sm font-black text-white">Volver a imaginar un proyecto de vida <ArrowRight className="ml-2 inline h-4 w-4 text-[#D9B991]" /></span></Link></div></div></section>

      <section id="impacto" className="bg-[#2D2528] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 sm:py-20 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-8"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-[#D9B991]">Impacto verificable</p><h2 className="mt-3 text-4xl font-black leading-[1.02] sm:text-6xl">No son cifras.<br /><em className="font-serif font-medium text-[#D9B991]">Son vidas.</em></h2><p className="mt-5 max-w-sm text-sm leading-relaxed text-slate-300">Conoce nuestras historias, jornadas y resultados en territorio.</p><Link href="/galeria" className="mt-6 inline-flex items-center gap-2 text-xs font-black text-[#D9B991]">Ver historias de impacto <ArrowRight className="h-4 w-4" /></Link></div><div className="grid grid-cols-2 gap-5 sm:grid-cols-4">{[['450+', 'Mujeres orientadas'], ['310+', 'Rutas activadas'], ['180+', 'Acciones de apoyo'], ['65', 'Procesos de autonomía']].map(([value, label]) => <div key={label} className="border-t border-white/20 pt-4"><strong className="font-serif text-4xl font-medium sm:text-5xl">{value}</strong><span className="mt-2 block max-w-[120px] text-[10px] font-bold uppercase tracking-wider text-slate-300">{label}</span></div>)}</div></div></section>

      <section id="apoyar" className="mx-auto max-w-7xl px-6 py-14 sm:py-20 lg:px-8"><div className="grid gap-6 rounded-[2rem] bg-[#F3E6DF] p-7 sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-senda-pink">Haz parte del cambio</p><h2 className="mt-2 max-w-2xl text-3xl font-black tracking-tight text-senda-purple-dark sm:text-5xl">Tu aporte puede convertirse en una acción concreta.</h2><p className="mt-4 max-w-xl text-sm leading-relaxed text-slate-600">Apoya atención, protección, salud y autonomía para mujeres y niñas en Cartagena.</p></div><Link href="/donar" className="inline-flex items-center justify-center gap-2 rounded-full bg-senda-pink px-7 py-4 text-sm font-black text-white shadow-glass-pink transition-all hover:-translate-y-0.5 hover:bg-senda-pink-dark"><HeartHandshake className="h-5 w-5" /> Quiero apoyar</Link></div></section>

      <section id="transparencia" className="mx-auto max-w-7xl px-6 pb-4 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-4 border-t border-[#e6dcd4] pt-7 text-xs"><span className="font-black text-senda-purple-dark">También puedes conocer:</span><div className="flex flex-wrap gap-x-5 gap-y-2 font-bold text-slate-500"><Link href="/nosotros" className="hover:text-senda-pink">Quiénes somos</Link><Link href="/ruta-cartagena" className="hover:text-senda-pink">Rutas en Cartagena</Link><Link href="/caribe-seguro/aliados" className="hover:text-senda-pink">Aliados</Link><Link href="/donar" className="hover:text-senda-pink">Donaciones</Link></div></div></section>
    </div>
  );
}
