import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, HeartHandshake } from 'lucide-react';
import { getProgram, programs } from '@/lib/programs';
import { notFound } from 'next/navigation';

export function generateStaticParams() { return programs.map(({ slug }) => ({ slug })); }

export default function ProgramaInterna({ params }: { params: { slug: string } }) {
  const program = getProgram(params.slug); if (!program) notFound();
  return <div className="bg-[#fbf8f3]"><section className="border-b border-[#ddd4ca] bg-[#f4eee7] py-8"><div className="senda-shell"><Link href="/programas" className="inline-flex items-center gap-2 text-sm font-bold text-[#6e3f58]"><ArrowLeft className="h-4 w-4"/>Todos los programas</Link></div></section>
    <section className="senda-shell grid gap-10 py-14 lg:grid-cols-[.95fr_1.05fr] lg:py-24"><div className="lg:py-8"><p className="senda-eyebrow">Programa {program.number} · {program.focus}</p><h1 className="mt-3 font-serif text-5xl font-semibold leading-[.95] tracking-tight text-[#26231f] sm:text-7xl">{program.title}</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#6c665f]">{program.summary}</p><Link href={`/agendar-cita?programa=${encodeURIComponent(program.title)}`} className="senda-button senda-button--primary mt-8">Solicitar orientación <ArrowRight/></Link></div><div className="relative min-h-[340px] overflow-hidden rounded-[28px] border-8 border-[#fffdf9] shadow-xl sm:min-h-[470px]"><Image src={program.image} alt={program.imageAlt} fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw"/></div></section>
    <section className="bg-[#203c3d] py-16 text-white"><div className="senda-shell"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#d9b991]">Así funciona la ruta</p><ol className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{program.route.map((step, index) => <li key={step} className="border-t border-white/20 pt-4"><span className="text-xs font-bold text-[#d9b991]">0{index + 1}</span><p className="mt-4 text-sm leading-6 text-[#edf4f0]">{step}</p></li>)}</ol></div></section>
    <section className="senda-section"><div className="senda-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="senda-eyebrow">Qué incluye</p><h2 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-[#26231f]">Acciones pensadas para cuidar y avanzar.</h2></div><ul className="space-y-4">{program.actions.map(action => <li key={action} className="flex gap-3 rounded-2xl border border-[#ddd4ca] bg-[#fffdf9] p-4 text-sm leading-6 text-[#544e48]"><Check className="mt-0.5 h-5 w-5 shrink-0 text-[#6e3f58]"/>{action}</li>)}</ul></div></section>
    {program.slug === 'proyecto-de-vida-y-autonomia' && <ProductiveLines />}
    <section className="bg-[#f4eee7] py-16 sm:py-24"><div className="senda-shell"><div className="mb-9 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="senda-eyebrow">Galería ilustrativa</p><h2 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-[#26231f]">Así se ve el acompañamiento.</h2></div><p className="max-w-sm text-xs leading-5 text-[#6c665f]">Estas imágenes representan actividades del programa. Reemplázalas por fotografías autorizadas de la Fundación para documentar el impacto real.</p></div><div className="grid gap-4 md:grid-cols-3">{program.gallery.map(item => <figure key={item.src} className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="relative h-64"><Image src={item.src} alt={item.alt} fill className="object-cover" sizes="(max-width: 768px) 100vw, 33vw"/></div><figcaption className="p-4 text-sm font-semibold text-[#544e48]">{item.caption}</figcaption></figure>)}</div></div></section>
    <section className="senda-section"><div className="senda-shell flex flex-col justify-between gap-8 rounded-3xl bg-[#f0e1da] p-8 sm:p-12 lg:flex-row lg:items-center"><div><HeartHandshake className="h-8 w-8 text-[#6e3f58]"/><h2 className="mt-5 font-serif text-4xl font-semibold text-[#26231f]">¿Quieres hablar con alguien?</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#6c665f]">Podemos orientarte para identificar el siguiente paso más adecuado para ti.</p></div><Link href={`/agendar-cita?programa=${encodeURIComponent(program.title)}`} className="senda-button senda-button--primary">Solicitar orientación <ArrowRight/></Link></div></section>
  </div>;
}

function ProductiveLines() { const lines = [['Confección','Diseño, talento y oportunidad'],['Huerta','Sembramos vida'],['Piscicultura','Agua, alimento y futuro'],['Repostería','Creatividad que endulza vidas'],['Artesanías','Tradición, cultura y valor'],['Avicultura','Nutrición y bienestar']]; return <section className="border-y border-[#ddd4ca] bg-[#fffdf9] py-16 sm:py-24"><div className="senda-shell"><p className="senda-eyebrow">Infografía · líneas productivas</p><div className="mt-3 grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="font-serif text-4xl font-semibold leading-tight tracking-tight text-[#26231f]">Mujeres que construyen oportunidades.</h2><p className="mt-5 text-sm leading-7 text-[#6c665f]">Formación, producción, comercialización y autonomía. Cada participante puede explorar una línea principal y rotar por otras áreas según sus intereses y metas.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{lines.map(([title, subtitle], index) => <article key={title} className="min-h-36 rounded-2xl border border-[#ddd4ca] bg-[#f4eee7] p-5"><span className="text-xs font-bold text-[#6e3f58]">0{index + 1}</span><h3 className="mt-6 font-serif text-xl font-semibold text-[#26231f]">{title}</h3><p className="mt-1 text-xs leading-5 text-[#6c665f]">{subtitle}</p></article>)}</div></div><div className="mt-9 grid gap-4 border-t border-[#ddd4ca] pt-7 text-sm text-[#544e48] sm:grid-cols-3"><p><b>Rotación y elección</b><br/><span className="text-[#6c665f]">Cada mujer define un camino de formación.</span></p><p><b>Infraestructura y apoyo</b><br/><span className="text-[#6c665f]">Herramientas, espacios, capacitación y acompañamiento.</span></p><p><b>Impacto</b><br/><span className="text-[#6c665f]">Seguridad alimentaria, ingresos y fortalecimiento comunitario.</span></p></div></div></section>; }
